# Generated by Django 5.2 on 2026-04-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.UUIDField(unique=True, verbose_name='JWT Token ID')),
                ('token_type', models.CharField(max_length=16, verbose_name='Token Type')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Blacklisted Token',
                'verbose_name_plural': 'Blacklisted Tokens',
                'db_table': 'blacklisted_tokens',
            },
        ),
    ]
