# Generated by Django 5.2 on 2026-04-30 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_majorclassmanagement_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='新会话', max_length=255, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='users.teacher', verbose_name='所属教师')),
            ],
            options={
                'verbose_name': '教师聊天会话',
                'verbose_name_plural': '教师聊天会话',
                'db_table': 'teacher_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.teacherchatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '教师聊天消息',
                'verbose_name_plural': '教师聊天消息',
                'db_table': 'teacher_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
