# Generated by Django 5.2 on 2026-04-30 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_devicetelemetry'),
        ('users', '0007_majorclassmanagement_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='AI评分')),
                ('teacher_score', models.FloatField(blank=True, null=True, verbose_name='教师评分')),
                ('final_score', models.FloatField(blank=True, null=True, verbose_name='最终评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.student', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='users.teacher', verbose_name='评分教师')),
            ],
            options={
                'verbose_name': '课程成绩',
                'verbose_name_plural': '课程成绩',
                'db_table': 'course_grades',
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='uniq_course_student_grade')],
            },
        ),
    ]
