# Generated by Django 5.2 on 2026-04-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursegrade'),
        ('users', '0008_teacherchatsession_teacherchatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCalendarOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('day_type', models.CharField(choices=[('work', '工作(班)'), ('rest', '休息(休)')], max_length=10, verbose_name='类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_overrides', to='users.teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师日历设置',
                'verbose_name_plural': '教师日历设置',
                'db_table': 'teacher_calendar_overrides',
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='uniq_teacher_date_override')],
            },
        ),
    ]
