# Generated by Django 5.2 on 2026-04-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_teachercalendaroverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercalendaroverride',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='teachercalendaroverride',
            name='day_type',
            field=models.CharField(choices=[('work', '工作(班)'), ('rest', '休息(休)'), ('default', '默认')], default='default', max_length=10, verbose_name='类型'),
        ),
    ]
